first_names = [
    "Emma", 
    "Noah", 
    "Olivia", 
    "Liam", 
    "Ava", 
    "William", 
    "Sophia", 
    "Mason", 
    "Isabella", 
    "James", 
    "Mia", 
    "Benjamin", 
    "Charlotte", 
    "Jacob", 
    "Abigail", 
    "Michael", 
    "Emily", 
    "Elijah", 
    "Harper", 
    "Ethan", 
    "Amelia", 
    "Alexander", 
    "Evelyn", 
    "Oliver", 
    "Elizabeth", 
    "Daniel", 
    "Sofia", 
    "Matthew", 
    "Avery", 
    "Aiden", 
    "Ella", 
    "Jackson", 
    "Madison", 
    "Logan", 
    "Scarlett", 
    "Connor", 
    "Victoria", 
    "Luke", 
    "Aria", 
    "Jayden", 
    "Grace", 
    "Isaiah", 
    "Chloe", 
    "Caleb", 
    "Natalie", 
    "Nicholas", 
    "Addison", 
    "Eli", 
    "Aubree", 
    "Aaron", 
    "Brooklyn", 
    "Isaac", 
    "Lily", 
    "Ryan", 
    "Eleanor"
]


last_names = [
    "Smith", 
    "Johnson", 
    "Williams", 
    "Jones", 
    "Brown", 
    "Davis", 
    "Miller", 
    "Wilson", 
    "Moore", 
    "Taylor", 
    "Anderson", 
    "Thomas", 
    "Jackson", 
    "White", 
    "Harris", 
    "Martin", 
    "Thompson", 
    "Garcia", 
    "Martinez", 
    "Robinson", 
    "Clark", 
    "Rodriguez", 
    "Lewis", 
    "Lee", 
    "Walker", 
    "Hall", 
    "Allen", 
    "Young", 
    "Hernandez", 
    "King", 
    "Wright", 
    "Lopez", 
    "Hill", 
    "Scott", 
    "Green", 
    "Adams", 
    "Baker", 
    "Nelson", 
    "Carter", 
    "Mitchell", 
    "Perez", 
    "Roberts", 
    "Turner", 
    "Phillips", 
    "Campbell", 
    "Parker", 
    "Evans", 
    "Edwards", 
    "Collins"
]




customer_params = {
    'adress_id': None,
    'created_by_id': 4,
    'created_date': None,
    'dob': None,
    'email': None,
    'esd': None,
    'first_name': '',
    'gender': '',
    'id': None,
    'id_passport': '',
    'last_name': '',
    'martial_status': '',
    'phone_no': '',
    'position': None,
    'salaty': None,
    'social_security_no_pesel': '',
    'work_status': '',
    'workplace_id': None
    }

product_params = {
    'owner_id': 1,
    'global_interest_rate_dec': Decimal('5.25'),
    'lombard_rate_dec': Decimal('5.75'),
    'product_name': 'L1',
    'amount_requested': 10000,
    'loan_period': 24,
    'created_date': datetime.date.today(),
}

workplace_params = {
    'adress_id': None,
    'email': None,
    'id': None,
    'id_nip': '',
    'name': '',
    'phone_no': ''
    }

adress_params = {
    'building_no': '',
    'city': '',
    'id': None,
    'street': '',
    'zip_code': ''
    }