# Generated by Django 4.0.4 on 2022-06-04 05:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=50)),
                ('building_no', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=2)),
                ('social_security_no_pesel', models.IntegerField(unique=True, verbose_name='PESEL')),
                ('id_passport', models.CharField(max_length=10, unique=True, verbose_name='ID serial number or Passport serial number')),
                ('martial_status', models.CharField(choices=[('md', 'maiden'), ('dv', 'divorcee'), ('mr', 'married'), ('wd', 'widow')], max_length=2)),
                ('work_status', models.CharField(choices=[('ft', 'Full-Time'), ('pt', 'Part-Time'), ('rt', 'Retired'), ('dp', 'Disablement Pension')], max_length=2)),
                ('esd', models.DateField(verbose_name='Employment start date')),
                ('salaty', models.IntegerField()),
                ('position', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField(unique=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('adress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.adress')),
            ],
        ),
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_nip', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField(unique=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('adress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.adress')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=2)),
                ('social_security_no_pesel', models.IntegerField(unique=True, verbose_name='PESEL')),
                ('id_passport', models.CharField(max_length=10, unique=True, verbose_name='ID serial number or Passport serial number')),
                ('phone_no', models.IntegerField(unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('information', models.TextField(blank=True, null=True)),
                ('adress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.adress')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_interest_rate', models.FloatField(default=5.25, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Central banks\n interest rate in %')),
                ('lombard_rate', models.FloatField(default=5.75, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Central banks lombard\n interest rate in %')),
                ('product_name', models.CharField(choices=[('L1', 'Loan'), ('L2', 'Loan - good Credit Rating')], default='L1', max_length=2)),
                ('amount_requested', models.IntegerField(default=10000, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(50000)])),
                ('loan_period', models.IntegerField(choices=[(6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48)], default=24)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userinfo'),
        ),
        migrations.AddField(
            model_name='customer',
            name='workplace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workplace'),
        ),
    ]
