# Generated by Django 4.0.4 on 2022-05-23 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='some_st2uff',
        ),
        migrations.RemoveField(
            model_name='product',
            name='some_stu2ff',
        ),
        migrations.RemoveField(
            model_name='product',
            name='some_stuff',
        ),
        migrations.AddField(
            model_name='product',
            name='ammount_borrowed',
            field=models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(30000)]),
        ),
    ]
