# Generated by Django 4.0.4 on 2022-05-23 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_product_some_st2uff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ammount_borrowed',
            new_name='ammount_requested',
        ),
        migrations.AddField(
            model_name='product',
            name='interest_rate',
            field=models.FloatField(default=3.5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Interest rate in %'),
        ),
        migrations.AddField(
            model_name='product',
            name='loan_period',
            field=models.IntegerField(choices=[(6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48)], default=6, max_length=2),
        ),
    ]
