# Generated by Django 4.0.4 on 2022-05-23 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_loan_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='interest_rate',
            field=models.FloatField(default=3.5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Default interest rate in %'),
        ),
    ]
