# Generated by Django 4.0.4 on 2022-05-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_product_interest_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(choices=[('CC', 'Credit Card'), ('L1', 'Loan - to 10 000'), ('L2', 'Loan - over 10 000')], default='CC', max_length=2),
        ),
    ]
