# Generated by Django 4.0.4 on 2022-05-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(choices=[('CC', 'Credit Card'), ('L1', 'Loan'), ('L2', 'Loan - good Credit Rating')], default='CC', max_length=2),
        ),
    ]
