# Generated by Django 4.0.4 on 2022-05-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_product_ammount_requested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(choices=[('L1', 'Loan'), ('L2', 'Loan - good Credit Rating')], default='L1', max_length=2),
        ),
    ]
