# Generated by Django 4.0.4 on 2022-05-26 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_product_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workplace',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='workplace',
        ),
        migrations.AddField(
            model_name='customer',
            name='workplace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workplace'),
        ),
    ]
