# Generated by Django 4.0.4 on 2022-05-27 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_customer_email_workplace_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customer'),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='adress',
        ),
        migrations.AddField(
            model_name='customer',
            name='adress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.adress'),
        ),
        migrations.RemoveField(
            model_name='workplace',
            name='adress',
        ),
        migrations.AddField(
            model_name='workplace',
            name='adress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.adress'),
        ),
    ]
